(env
 (_
  (flags
   (:standard
    -w
    +comment-start
    -w
    +comment-not-end
    -w
    +ignored-partial-application
    -w
    +labels-omitted
    -w
    +method-override
    -w
    +partial-match
    -w
    +missing-record-field-pattern
    -w
    +non-unit-statement
    -w
    +redundant-case
    -w
    +redundant-subpat
    -w
    +instance-variable-override
    -w
    +illegal-backslash
    -w
    +implicit-public-methods
    -w
    +unerasable-optional-argument
    -w
    +undeclared-virtual-method
    -w
    +not-principal
    -w
    +non-principal-labels
    -w
    +ignored-extra-argument
    -w
    +nonreturning-statement
    -w
    +preprocessor
    -w
    +useless-record-with
    -w
    +bad-module-name
    -w
    +unused-var
    -w
    +unused-var-strict
    -w
    +wildcard-arg-to-constant-constr
    -w
    +module-linked-twice
    -w
    +unused-value-declaration
    -w
    +unused-open
    -w
    +unused-type-declaration
    -w
    +unused-for-index
    -w
    +unused-ancestor
    -w
    +unused-constructor
    -w
    +unused-extension
    -w
    +unused-rec-flag
    -w
    +nonoptional-label
    -w
    +bad-env-variable
    -w
    +attribute-payload
    -w
    +no-cmi-file
    -w
    +unexpected-docstring
    -w
    +wrong-tailcall-expectation
    -w
    +fragile-literal-pattern
    -w
    +misplaced-attribute
    -w
    +duplicated-attribute
    -w
    +inlining-impossible
    -w
    +unreachable-case
    -w
    +ambiguous-var-in-pattern-guard
    -w
    +unused-module
    -w
    +unboxable-type-in-prim-decl
    -w
    +constraint-on-gadt
    -w
    +unused-open-bang
    -w
    +unused-functor-parameter
    -w
    +unused-field
    -w
    -name-out-of-scope
    -strict-sequence
    -strict-formats))))
