(** Extensions to [Stdlib.Seq] with utility functions. *)

include Stdlib.Seq

(** The bind operator for sequences, also known as [concat_map]. *)
let bind = concat_map

(** An iteration over the cross-product of [seq] with itself, excluding pairs
    (x, x) of the same element. For instance, [self_cross_product [1; 2; 3]]
    will iterate over [(1, 2), (1, 3), (2, 3)] Note that the sequence needs to
    be persistent, otherwise result is unspecified. *)
let self_cross_product seq =
  let rec aux seq =
    match seq () with
    | Nil -> empty
    | Cons (x, seq) -> append (map (fun y -> (x, y)) seq) (aux seq)
  in
  aux seq

(** Create a sequence of values generated by a function up to a given bound.
    Similar to [Stdlib.Seq.init] but the input parameter is a [Z.t] instead of
    an [int]. *)
let init_z n f =
  let rec init_aux_z f i j () =
    if Z.lt i j then Cons (f i, init_aux_z f (Z.succ i) j) else Nil
  in
  if Z.lt n Z.zero then invalid_arg "Seq.init_z" else init_aux_z f Z.zero n

(** Compare the length of a sequence with a given number. Returns 1 if the
    sequence is longer, 0 if it has the same length, and -1 if it is shorter.
    The sequence must be persistent, otherwise the result is unspecified. Will
    only traverse the sequence up to [n + 1] elements, so it is efficient even
    for infinite sequences. *)
let compare_length_with seq n =
  let rec aux seq n =
    if n < 0 then 1
    else
      match seq () with
      | Nil -> if n = 0 then 0 else -1
      | Cons (_, seq) -> aux seq (n - 1)
  in
  aux seq n
