name: Open PR

permissions:
  issues: write
  pull-requests: write
  
on:
  pull_request:
    branches: ["main"]
    types: [closed]
  
jobs:
  kill-documentation-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Make empty doc folder
        run: mkdir empty
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          destination_dir: ./api/pr-${{ github.event.pull_request.number }}
          
      - name: Upload documentation to api/branch
        uses: actions/deploy-pages@v4
        id: deploy_pages
        
      - run: echo "Successfully updated documentation at ${{steps.deploy_pages.outputs.page_url}}"
            